apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  type: LoadBalancer
  ports:
    - port: 3000        # Port exposed inside the cluster
      targetPort: 3000  # Port your frontend container listens on
      protocol: TCP
